"""Initial migration

Revision ID: 6a95d7308ea3
Revises: 
Create Date: 2025-04-05 19:08:47.775239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6a95d7308ea3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Determine which JSON type to use based on the database
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        json_type = postgresql.JSONB(astext_type=sa.Text())
    else:
        json_type = sa.JSON()
    
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('result_path', sa.String(length=255), nullable=True),
    sa.Column('result_data', json_type, nullable=True),
    sa.Column('has_result', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_status_created_at', 'task', ['status', 'created_at'])
    op.create_index('ix_task_platform_created_at', 'task', ['platform', 'created_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_platform_created_at', table_name='task')
    op.drop_index('ix_task_status_created_at', table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
