"""
Belief System & Stance Analyzer
Profiles a target's Worldview: Political Alignment, Social Values, and Ethical Framework.
Forecasts reactions to future events.
"""

import json
import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class BeliefSystemAnalyzer:
    """
    Analyzes political orientation, social values, and ethical frameworks.
    Forecasts reactions to future events.
    """
    
    def __init__(self, openrouter_client):
        self.ai = openrouter_client
    
    def analyze_belief_system(self, content_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Comprehensive analysis of political, social, and ethical stance.
        
        Args:
            content_data: Aggregated content from deep dossier collection.
                          Should include: posts, transcripts, comments, bio.
                          
        Returns:
            Dict containing Worldview Profile.
        """
        
        # Extract relevant text for analysis to optimize token usage
        # Focusing on opinions, controversial topics, and values
        text_samples = self._extract_opinionated_text(content_data)
        
        if not text_samples:
            return {"error": "Insufficient data for belief analysis"}
            
        system_prompt = """You are an expert Political Scientist and Sociologist specializing in digital discourse analysis.
Your goal is to accurately map the subject's worldview based on their digital footprint.
Analyze for nuance - avoid simple labeling if the subject shows complexity.
Be objective and analytical."""

        prompt = f"""
        Analyze this digital footprint to build a comprehensive Worldview Profile.
        
        CONTENT SAMPLES:
        {json.dumps(text_samples, indent=2)}
        
        Provide a structured JSON output with the following sections:
        
        1. POLITICAL COMPASS
           - economic_axis: Score -10 (Far Left) to +10 (Far Right)
           - social_axis: Score -10 (Authoritarian) to +10 (Libertarian)
           - label: e.g., "Left-Libertarian", "Centrist", "Conservative"
           - confidence: 0.0 to 1.0
           - key_policy_stances: {{"climate": "alert", "economy": "regulation", ...}}
           
        2. SOCIAL VALUES (The 5 Moral Foundations)
           - care_harm: Score 0-10 (High focus on care/protection)
           - fairness_cheating: Score 0-10 (High focus on justice/equality)
           - loyalty_betrayal: Score 0-10 (High focus on group/nation)
           - authority_subversion: Score 0-10 (High focus on tradition/order)
           - sanctity_degradation: Score 0-10 (High focus on purity/sacredness)
           
        3. ETHICAL FRAMEWORK
           - primary_framework: "Utilitarian", "Deontological", "Virtue Ethics", "Nihilism", etc.
           - reasoning_style: How they justify opinions (e.g., "appeals to emotion", "data-driven", "principled")
           
        4. CONTROVERSIAL TOPICS
           - supported_causes: []
           - opposed_causes: []
           - blind_spots: Potential inconsistencies in their logic
           
        5. PREDICTION MODEL PARAMS
           - openness_to_change: Score 0-10
           - radicalization_risk: Score 0-10
           - echo_chamber_score: Score 0-10 (How insular are their views?)
        
        Format as pure JSON.
        """
        
        return self.ai.analyze(prompt, system_prompt, model_type="belief_analysis")

    def forecast_stance(self, profile: Dict[str, Any], unexpected_event: str) -> Dict[str, Any]:
        """
        Predict how the target will react/align on a hypothetical future event.
        
        Args:
            profile: The Belief System Profile generated by analyze_belief_system()
            unexpected_event: Description of the future event (e.g. "Global ban on crypto")
            
        Returns:
            Dict prediction with reasoning.
        """
        
        system_prompt = """You are a Predictive Behavioral Analyst. 
        Using the provided psychological and political profile, simulate exactly how this specific individual would react."""
        
        prompt = f"""
        TARGET PROFILE:
        {json.dumps(profile, indent=2)}
        
        HYPOTHETICAL EVENT:
        "{unexpected_event}"
        
        Forecast the target's reaction.
        
        Provide JSON output:
        1. predicted_stance: "Support", "Oppose", "Neutral", "Conflicted"
        2. public_reaction_intensity: Score 0-10 (0=ignore, 10=active protest)
        3. predicted_argument: The exact logic/rhetoric they will likely use
        4. likelihood_score: Confidence in this prediction (0-1)
        5. potential_contradiction: Would this event expose hypocracy based on past views?
        """
        
        return self.ai.analyze(prompt, system_prompt, model_type="belief_analysis")
        
    def _extract_opinionated_text(self, data: Dict) -> List[str]:
        """Helper to extract text likely to contain values/opinions"""
        texts = []
        
        # 1. Profile Bio (often contains identity signals like flags, pronouns, slogans)
        if data.get('profile'):
            bio = data['profile'].get('bio') or data['profile'].get('description')
            if bio: texts.append(f"BIO: {bio}")
            
        # 2. Transcripts (highest fidelity for detailed thoughts)
        for t in data.get('transcripts', []):
            txt = t.get('transcript', {}).get('transcript', '')
            if len(txt) > 50:
                texts.append(f"TRANSCRIPT: {txt[:1000]}") # Truncate for token limits
                
        # 3. Text Posts (Twitter/Threads/BlueSky/LinkedIn/Facebook)
        for item in data.get('content', []):
            # Check for text fields
            text = (item.get('text') or 
                   item.get('content') or 
                   item.get('caption') or 
                   item.get('description'))
            
            if text and len(text) > 20: # Skip very short/empty captions
                # Filter for opinion markers could happen here, but LLM is robust enough
                texts.append(f"POST: {text}")
                
        return texts[:20]  # Limit to 20 most relevant samples for context window
